url: "https://jinhankim.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jinhan Kim | Software Engineering" # the name of your site, e.g. ACME Corp.


sass:
    style: compressed
    sass_dir: _sass
    
scholar:
  style: apa
  bibliography_template: bibtemplate
  sort_by: year,month
  order: descending  
  repository: ./assets/files/papers
  bibtex_options: 
    parse_names : false